server:
  port: 8080
spring:
  application:
    name: "PlazoletaMsUsers"
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:mysql://localhost:3306/plazoleta_users?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    username: "plazoleta_user"
    password: "plazoleta123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
        format_sql: true
    databasePlatform: "org.hibernate.dialect.MySQL8Dialect"
jwt:
  secret: "mySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm"
  expiration: 86400000
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
login:
  maxAttempts: 3
  lockout-duration: 15 #minutes
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: false